#!/bin/bash
function log {
    echo "Snap: $*"
}

# Check for disconnected interfaces
for interface in audio-playback browser-sandbox browser-support \
    gsettings home network opengl removable-media; do
    if ! snapctl is-connected $interface; then
        log "Interface $interface is disconnected! Fix with 'snap connect typora:$interface'"
    fi
done

# Execute snap command
exec "$@"
