# https://snapcraft.io/docs/snapcraft-yaml-reference
name: typora
summary: A minimal Markdown reading and writing app
description: |
  Typora is a minimal markdown editor, providing new ways for reading and
  writing markdown. It is currently in beta.

  Typora is commercial software (not open source), but is free during beta.
  Typora on GitHub supports collaboration between its developer, Abner Lee,
  and its user community, providing a place to transparently report issues,
  collect feedback and discuss future direction. It also provides open
  source resources for user customization of themes.

adopt-info: typora
base: core20
grade: stable
confinement: strict
architectures: 
  - build-on: amd64
  - build-on: arm64

plugs:
  browser-sandbox:
    allow-sandbox: false
    interface: browser-support
  #system-files:
  #  interface: system-files
  #  read:
  #  - /usr/bin
  #  - /usr/local/bin

layout:
  /usr/share/pandoc/data:
    bind: $SNAP/usr/share/pandoc/data

apps:
  typora:
    command: wrapper $SNAP/typora/Typora --no-sandbox --disable-gpu
    extensions: [gnome-3-38]
    environment:
      DISABLE_WAYLAND: '1'
    plugs:
      - browser-support
      - browser-sandbox
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - x11
      - opengl
      - home
      - system-backup
      - system-observe
      - network
      - gsettings
      - audio-playback
      - removable-media
      # - system-files

parts:
  typora:
    source: 
    - on amd64: https://download.typora.io/linux/Typora-linux-x64.tar.gz?0911
    - on arm64: https://download.typora.io/linux/Typora-linux-arm64.tar.gz
    source-type: tar
    plugin: dump
    override-build: |
      snapcraftctl build
      snapcraftctl set-version $(cat resources/package.json | jq -r .version)
    build-packages:
      - jq
    organize:
      '*': typora/

  wrapper:
    source: scripts
    plugin: dump
    stage-packages:
      - jq
      - libnspr4
      - libnss3
      - libxss1
      - pandoc
      - pandoc-data

  cleanup:
    after: [typora, wrapper]
    plugin: nil
    build-snaps: [core20, gnome-3-38-2004]
    override-prime: |
      find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $SNAPCRAFT_PRIME/usr/share/man/ -type f -delete
      find $SNAPCRAFT_PRIME/ -type d -empty -delete
      sudo chown root $SNAPCRAFT_PRIME/typora/chrome-sandbox
      chmod 755 $SNAPCRAFT_PRIME/typora/chrome-sandbox
