name: typora
summary: A minimal Markdown reading and writing app
description: |
  Typora gives you a seamless experience as both a markdown reader and a
  writer. It removes the preview window, mode switcher, syntax symbols of
  markdown source code, and all other unnecessary distractions. Instead, it
  provides a real live preview feature to help you concentrate on the content
  itself.

adopt-info: typora
base: core24
grade: stable
confinement: strict
platforms:
  amd64:
  arm64:
compression: lzo

plugs:
  shared-memory:
    interface: shared-memory
    private: true

layout:
  /usr/share/pandoc/data:
    bind: $SNAP/usr/share/pandoc/data

apps:
  typora:
    command: Typora --no-sandbox
    extensions: [gnome]
    plugs:
      - audio-playback
      - home
      - network
      - removable-media

parts:
  typora:
    source:
    - on amd64: https://download.typora.io/linux/Typora-linux-x64.tar.gz?0911
    - on arm64: https://download.typora.io/linux/Typora-linux-arm64.tar.gz?0228
    source-type: tar
    plugin: dump
    override-build: |
      craftctl default
      craftctl set version=$(cat resources/package.json | jq -r .version)
    build-packages:
      - jq
    stage-packages:
      - pandoc
      - pandoc-data
